### ISSUE TITLE
StatWorker_Mass.cs edit: Add support for Dead pawns.

### ISSUE THREAD

**Issue by jagerguy36** [emipa606/SYRIndividuality#4]
Issue: Currently, when a pawn dies the individuality mass stat does not apply because StatWorker_Mass.cs tries to get CompIndividuality from the Corpse. This fix makes it so that the Individuality mass change also applies correctly to the Corpse.

    public override float GetValueUnfinalized(StatRequest req, bool applyPostProcess = true)
    {

        var compIndividuality = req.Thing.TryGetComp<CompIndividuality>();
        if (req.Thing.def.IsCorpse)
        {
            var corpse = req.Thing as Corpse;
            compIndividuality = corpse.InnerPawn.TryGetComp<CompIndividuality>();
        }
        if (compIndividuality != null)
        {
            return base.GetValueUnfinalized(req, applyPostProcess) +
                   compIndividuality.BodyWeight;
        }
        return base.GetValueUnfinalized(req, applyPostProcess);
    }

    public override string GetExplanationUnfinalized(StatRequest req, ToStringNumberSense numberSense)
    {
        var stringBuilder = new StringBuilder();
        var compIndividuality = req.Thing.TryGetComp<CompIndividuality>();
        if (req.Thing.def.IsCorpse)
        {
            var corpse = req.Thing as Corpse;
            compIndividuality = corpse.InnerPawn.TryGetComp<CompIndividuality>();
        }
        if (compIndividuality == null)
        {
            return base.GetExplanationUnfinalized(req, numberSense);
        }
        stringBuilder.AppendLine("BodyWeightOffset".Translate() + ": " +
                                 stat.ValueToString(compIndividuality.BodyWeight));
        return $"{base.GetExplanationUnfinalized(req, numberSense)}\n{stringBuilder.ToString().TrimEndNewlines()}";
    }

**Comment by emipa606** [comment]
Should be fixed in 69da836, thanks!
